name: test
on: 
  push:
    branches:
    - 'master'
    schedule:
    - cron:  '43 0 * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: install
      run: |
        echo '${{ secrets.WEATHERKEY }}' > testkey.json
        echo '''${{ secrets.WEATHERURL }}''' > weatherurl.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python test
      run: |
        python3 wh_1.py